"""Add JobPostingConfig table

Revision ID: 1488c0604adc
Revises: e2507f2d536e
Create Date: 2025-06-05 10:33:40.517570

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1488c0604adc'
down_revision = 'e2507f2d536e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobpostingconfig',
    sa.Column('default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vector_store_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_base_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vector_search_top_k', sa.Integer(), nullable=False),
    sa.Column('vector_search_similarity_threshold', sa.Float(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobpostingconfig')
    # ### end Alembic commands ###
