"""add_email_config

Revision ID: 7230b8866190
Revises: c66ddcf6379a
Create Date: 2025-05-19 11:25:06.743345

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7230b8866190'
down_revision = 'c66ddcf6379a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailconfig',
    sa.Column('smtp_host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('smtp_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('from_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailconfig')
    # ### end Alembic commands ###
