"""Add subscription model

Revision ID: ce673a26f0aa
Revises: [will be generated]
Create Date: 2025-04-30 09:24:00.351938

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce673a26f0aa'
down_revision = '[will be generated]'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
