"""initial_migration

Revision ID: de4c808e7f14
Revises: aa0d7bea9351
Create Date: 2025-06-11 15:03:14.168068

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'de4c808e7f14'
down_revision = 'aa0d7bea9351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###